# Concatenating from separate Files

In [1]:
import pandas as pd

In [2]:
re_df1 = pd.read_csv('data/RealEstate1.csv')
re_df2 = pd.read_csv('data/RealEstate2.csv')
re_df3 = pd.read_csv('data/RealEstate3.csv')

In [3]:
realEstate = pd.concat([re_df1, re_df2, re_df3], axis=0, ignore_index=False)
realEstate

,ID,MLS,Location,Price,Bedrooms,Bathrooms,Size,Price SQ Ft,Status
0,1,143178,Santa Maria-Orcutt,375000,4,2,1963,191.03,Short Sale
1,2,143217,Santa Maria-Orcutt,330000,3,3,1900,173.68,Short Sale
2,3,143252,Santa Maria-Orcutt,199000,3,3,1450,137.24,Short Sale
3,4,143255,Santa Maria-Orcutt,165000,2,2,1000,165.00,Short Sale
0,5,143436,Templeton,1399000,4,3,6500,215.23,Foreclosure
1,6,143507,Santa Maria-Orcutt,255000,3,2,1218,209.36,Short Sale
2,7,143524,Cambria,325000,2,2,893,363.94,Short Sale
3,8,143534,Morro Bay,789000,3,3,2100,375.71,Foreclosure
0,9,143540,Nipomo,498000,4,3,2341,212.73,Short Sale
1,10,143884,Nipomo,430000,4,2,2168,198.34,Short Sale
2,11,143946,Paso Robles,539900,4,3,3032,178.07,Short Sale
3,12,144204,Pismo Beach,499000,3,2,1293,385.92,Short Sale
4,12,144238,Los Osos,275000,3,2,1200,229.17,Short Sale

In [8]:
realEstate[realEstate.columns[1]]

0    143178
1    143217
2    143252
3    143255
0    143436
1    143507
2    143524
3    143534
0    143540
1    143884
2    143946
3    144204
4    144238
Name: MLS, dtype: int64

In [5]:
realEstate['MLS']

0    143178
1    143217
2    143252
3    143255
0    143436
1    143507
2    143524
3    143534
0    143540
1    143884
2    143946
3    144204
4    144238
Name: MLS, dtype: int64

In [7]:
bedRooms = realEstate[realEstate['Bedrooms'] > 3]
bedRooms

,ID,MLS,Location,Price,Bedrooms,Bathrooms,Size,Price SQ Ft,Status
0,1,143178,Santa Maria-Orcutt,375000,4,2,1963,191.03,Short Sale
0,5,143436,Templeton,1399000,4,3,6500,215.23,Foreclosure
0,9,143540,Nipomo,498000,4,3,2341,212.73,Short Sale
1,10,143884,Nipomo,430000,4,2,2168,198.34,Short Sale
2,11,143946,Paso Robles,539900,4,3,3032,178.07,Short Sale