In [1]:
import pandas as pd
import numpy as np

In [9]:
# Load Dataset
df = pd.read_csv('data/Teen_Mental_Health_Dataset.csv')

In [10]:
# View Shape of Data
rows, columns = df.shape
print('Rows',rows)
print('Columns',columns)

Rows 1200
Columns 13

In [11]:
# View First 5 Entries
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [12]:
# View First 5 Entries
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [13]:
# column names , non-null counts ,data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 122.0 KB

In [14]:
df[df.columns[[0,2]]]

      age  daily_social_media_hours
0      14                       7.9
1      19                       1.9
2      17                       1.3
3      15                       7.4
4      15                       4.7
...   ...                       ...
1195   18                       6.8
1196   16                       2.3
1197   14                       1.7
1198   15                       3.9
1199   16                       4.7

[1200 rows x 2 columns]

In [15]:
df[['age','daily_social_media_hours']]

      age  daily_social_media_hours
0      14                       7.9
1      19                       1.9
2      17                       1.3
3      15                       7.4
4      15                       4.7
...   ...                       ...
1195   18                       6.8
1196   16                       2.3
1197   14                       1.7
1198   15                       3.9
1199   16                       4.7

[1200 rows x 2 columns]

In [16]:
df.iloc[:, [0,2]]

      age  daily_social_media_hours
0      14                       7.9
1      19                       1.9
2      17                       1.3
3      15                       7.4
4      15                       4.7
...   ...                       ...
1195   18                       6.8
1196   16                       2.3
1197   14                       1.7
1198   15                       3.9
1199   16                       4.7

[1200 rows x 2 columns]

In [17]:
# .loc[:-- all rows ,specified columns]
df.loc[:, ['age', 'daily_social_media_hours']]

      age  daily_social_media_hours
0      14                       7.9
1      19                       1.9
2      17                       1.3
3      15                       7.4
4      15                       4.7
...   ...                       ...
1195   18                       6.8
1196   16                       2.3
1197   14                       1.7
1198   15                       3.9
1199   16                       4.7

[1200 rows x 2 columns]

In [18]:
# View Descriptive Statistics
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000